import { NgModule } from '@angular/core';
import {
  MatToolbarModule, MatIconModule, MatButtonModule, MatSidenavModule, MatListModule, MatCardModule,
  MatFormFieldModule, MatInputModule, MatDialogModule, MatTooltipModule, MatMenuModule, MatProgressBarModule,
  MatStepperModule, MatTabsModule, MatTableModule, MatPaginatorModule, MatSelectModule, MatSnackBarModule,
  MatSlideToggleModule, MatExpansionModule, MatDatepickerModule, MatNativeDateModule, MatSliderModule,
  MatAutocompleteModule, MatChipsModule, MatBadgeModule, MatBottomSheetModule, MatGridListModule,
  MatCheckboxModule, MatRadioModule, MatButtonToggleModule
} from '@angular/material';

@NgModule({
  imports: [
    MatToolbarModule,
    MatIconModule,
    MatButtonModule,
    MatSidenavModule,
    MatListModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatDialogModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatMenuModule,
    MatProgressBarModule,
    MatStepperModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatTabsModule,
    MatTableModule,
    MatPaginatorModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatGridListModule,
    MatCheckboxModule,
    MatRadioModule,
    MatButtonToggleModule
  ],
  exports: [
    MatToolbarModule,
    MatIconModule,
    MatButtonModule,
    MatSidenavModule,
    MatListModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatDialogModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatMenuModule,
    MatProgressBarModule,
    MatStepperModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatTabsModule,
    MatTableModule,
    MatPaginatorModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatGridListModule,
    MatCheckboxModule,
    MatRadioModule,
    MatButtonToggleModule
  ]
})
export class MaterialModule {}

